# Generated by Django 5.1 on 2024-08-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gecko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_temperature', models.FloatField()),
                ('spawn_date', models.DateField()),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='father', to='gecko.gecko')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother', to='gecko.gecko')),
            ],
            options={
                'verbose_name': '해칭 정보',
                'verbose_name_plural': '해칭 정보 목록',
            },
        ),
    ]
