# Generated by Django 5.1 on 2024-08-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gecko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gecko',
            name='gender',
            field=models.CharField(choices=[('M', '수컷'), ('F', '암컷'), ('U', '미구분')], default='U', max_length=10),
        ),
    ]
